name: Generate Snake Animation

on:
# Runs automatically every day at midnight
schedule:
  - cron: "0 0 * * *"

# Allows you to manually trigger the workflow from the Actions tab
workflow_dispatch:

# Runs whenever you push to your main profile README
push:
  branches:
    - main
    - master

jobs:
build:
  runs-on: ubuntu-latest
  steps:
    # Check out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Generate the snake animation from your GitHub contributions
    - name: Generate Snake SVG
      uses: Platane/snk@v3
      with:
        github_user_name: Jos-Low   # <-- change this to your GitHub username
        outputs: |
          dist/snake.svg
          dist/snake-dark.svg?palette=github-dark

    # Push the generated files (snake.svg) to the output branch
    - name: Push Snake Animation to output branch
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
